### ISSUE TITLE
Package for EPEL

### ISSUE THREAD

**Issue by Kahn** [DanielAdolfsson/ndppd#10]
I would like to add an RPM spec and get the ndppd package into the EPEL package set for CentOS 7

**Comment by DanielAdolfsson** [comment]
Are you volunteering to get it into CentOS? =)

**Comment by Kahn** [comment]
Ha I forgot I raised this but yes I can do that if your keen.

**Comment by DanielAdolfsson** [comment]
Sorry about that, been quite busy the past few months.
It would be awesome with an rpm release as well, ndppd is already in Gentoo and Debian (among others).

**Comment by DanielAdolfsson** [comment]
I'm closing this issue. You're free to package this as an EPEL package if you like.
Ping me when and if you do :)

**Comment by meeuw** [comment]
FYI, I've created a package for Fedora:

https://github.com/meeuw/fedora-ndppd
https://copr.fedorainfracloud.org/coprs/meeuw/ndppd/

I'll see if I can build a package for Fedora EPEL (RHEL/Centos)

**Comment by DanielAdolfsson** [comment]
Good job, @meeuw!

**Comment by spritacco** [comment]
I'm seeing a weird problem on Centos 7 with ndppd. If I run a debug build it is working, but normal build does not. (I've also put selinux in permissive mode to avoid problems there.) Is anyone still maintain the code?

**Comment by DanielAdolfsson** [comment]
Are you running the latest release (0.2.5), or the latest commit?

**Comment by spritacco** [comment]
looks like I pulled "latest commit" 0.2.6
followed a howto that had me run this git command: git clone https://github.com/DanielAdolfsson/ndppd

**Comment by spritacco** [comment]
The strange thing is that I had done the same process about 6 months ago and had no problems at all.
Perhaps it's some library that has changed in Centos 7 more recently?

**Comment by SpareSimian** [comment]
ndppd is now in EPEL 8:

https://bugzilla.redhat.com/show_bug.cgi?id=1982772

It should be in EPEL 7 soon:

https://bugzilla.redhat.com/show_bug.cgi?id=2015160

**Comment by SpareSimian** [comment]
Package pushed to EPEL 7 this morning.

You can monitor issues reported to Red Hat's bugzilla for ndppd here: https://bugzilla.redhat.com/buglist.cgi?component=ndppd
