### ISSUE TITLE
Doesn't build with GCC 6: narrowing conversion

### ISSUE THREAD

**Issue by nirgal** [DanielAdolfsson/ndppd#11]
The original report is at: https://bugs.debian.org/811756 by Martin Michlmayr (HP).
I believe your are using Ubuntu so you'll get identical build flow:

```
This package fails to build with GCC 6.  GCC 6 has not been released
yet, but it's expected that GCC 6 will become the default compiler for
stretch.

Note that only the first error is reported; there might be more.  You
can find a snapshot of GCC 6 in experimental.  To build with GCC 6,
you can set CC=gcc-6 CXX=g++-6 explicitly.

You may be able to find out more about this issue at
https://gcc.gnu.org/gcc-6/changes.html

> sbuild (Debian sbuild) 0.67.0 (26 Dec 2015) on dl580gen9-02.hlinux
...
> g++ -c -Wdate-time -D_FORTIFY_SOURCE=2 -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -o src/iface.o src/iface.cc
> src/iface.cc: In static member function 'static ndppd::ptr<ndppd::iface> ndppd::iface::open_pfd(const string&)':
> src/iface.cc:153:5: error: narrowing conversion of '-1' from 'int' to '__u32 {aka unsigned int}' inside { } [-Wnarrowing]
>      };
>      ^
> 
> Makefile:37: recipe for target 'src/iface.o' failed
> make[1]: *** [src/iface.o] Error 1
```

**Comment by DanielAdolfsson** [comment]
Cool, I'll take a look

**Comment by florianl** [comment]
Hi!

I get the same error while compiling:

    + CFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic'
    + LDFLAGS='-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld'
    + make -j4
    g++ -c  -O3 -o src/logger.o src/logger.cc
    g++ -c  -O3 -o src/ndppd.o src/ndppd.cc
    g++ -c  -O3 -o src/iface.o src/iface.cc
    g++ -c  -O3 -o src/proxy.o src/proxy.cc
    src/iface.cc: In static member function 'static ndppd::ptr<ndppd::iface> ndppd::iface::open_pfd(const string&)':
    src/iface.cc:153:5: error: narrowing conversion of '-1' from 'int' to '__u32 {aka unsigned int}' inside { } [-Wnarrowing]

Kind regards,
 Florian

**Comment by kerneis** [comment]
Fails to build on openwrt for the same reason.

**Comment by DanielAdolfsson** [comment]
Fix committed

**Comment by nirgal** [comment]
Thank you Daniel :)
