### ISSUE TITLE
Daemon exits (after some time) on EdgeMax ERL-Lite

### ISSUE THREAD

**Issue by tbr** [DanielAdolfsson/ndppd#14]
Hi,

first of all I would like to thank you for writing this NDP Proxy. It's a very useful tool :)

Some context: I cross compiled ndppd for the UBNT EdgeMax ERL-Lite router (MIPS based) without any problems. However, after handling some ND packets, the ndppd daemon just exits (no error, other than the messages "Shutting down..." and "Bye" in the logs). When running on console in non-daemon mode, it works just fine. So I suspect that something is not 100% correct in de daemonize function.

After reading on http://www.netzmafia.de/skripten/unix/linux-daemon-howto.html, I decided to modify the daemonize function to also call the umask(0) and chdir("/") functions, in an attempt to resolve the issue. After doing so, the ndppd daemon mode works perfectly (on the EdgeMax).

So my request: Would you be willing to test and verify that these two extra calls actually do make a difference? I attached a patch in this post, which only modifies the "int daemonize()" function in ndppd.cc (and adds an extra include). It would be great to include these changes into the GIT repository (after verification).

Kind regards,
Tim Bruylants
[ndppd_daemon.patch.txt](https://github.com/DanielAdolfsson/ndppd/files/201011/ndppd_daemon.patch.txt)

**Comment by DanielAdolfsson** [comment]
Hey, thanks for the feedback.

ndppd shuts down whenever it receives a sigterm or sigint, and it would be interesting to know why it's being terminated. 

I don't see any problems with the changes you provided, so I'll implement it shortly.

**Comment by tbr** [comment]
Well, I don't know exactly either. Starting ndppd in daemon or non-daemon works perfectly, as long as the SSH terminal session (to the EdgeMax router) was open. Of course, non-daemon mode needs a terminal. However, for the daemon mode, each time after closing the SSH connection, the daemon exits after a few seconds/minutes (I don't have an exact timing here).

If you like, I will investigate a little bit further to see if I can find out what the actual cause is. No guarantees given :)

I can say that my patched ndppd version runs perfectly for over a week now on the EdgeMax, so I suppose the problem is caused by filesystem and/or umask issues, but that's more of a wild guess than it is a certainty.

**Comment by DanielAdolfsson** [comment]
I've added the changes to the latest commit.

Closing this issue as the changes are working on your machine.
Thanks for the patch :)
