### ISSUE TITLE
Session drops on NA timeout

### ISSUE THREAD

**Issue by gawen947** [DanielAdolfsson/ndppd#16]
Hi,

Thanks for saving our native IPv6 :)

Reading from the code (correct me if I am wrong), when a session enters the INVALID state, all subsequent solicitations messages matching the target address are ignored (proxy.cc:79) until the session is removed. Also advertisements are only taken into account if there is a matching session in the WAITING state (iface.cc:586). So if a WAITING session timeouts and goes INVALID, ndp messages for this target are not proxied for about 30s. This could be a problem on lossy links.

I made a small patch that modify the state machine so that:
- NA always switch the session to VALID (and reset timer).
- NS received when INVALID/WAITING always reset to WAITING (and send solicit).

That way a session can recover from a lost/timeout NA,  a session stays VALID for TTL after the last NA, and it is removed when no NS/NA have been received for a duration of TTL.

If that sounds OK for you, I can work on a pull request.

**Comment by DanielAdolfsson** [comment]
Hey, sorry about the late response.

It's been a while since I coded that, but I think one of the purposes with INVALID is to make sure there is some kind of upper limit as to how many NS should be forwarded inwards. 

Maybe we should use another TTL value for invalid entries, to allow for earlier retries?

**Comment by gawen947** [comment]
Is there a security reason behind this? Blacklisting targets because they did not respond in time or packet drop occurred seems a bit harsh to me. If the NS or NA is dropped inwards, no matter how long the timeout is for WAITING, the session will go INVALID (because NS retransmission are ignored). Also if we want to reduce the INVALID TTL, it should be within the NS retries period to avoid packet drop in upper layers. That is ~3s on Linux so in case of a single NA/NS drop, we need WAITING timeout + INVALID TTL < 3s. It may also change from one network to another.

Another solution would be to use two states, WAITING and VALID.

In the WAITING state all NS are forwarded and reset the timer. So that we can wait up to WAITING timeout after the last NS retransmission.

In the VALID state all NS are proxied from the cache entry. It stays VALID for a duration of cache TTL and is then removed. Receiving a matching NA resets the timer as it refreshes the cache entry.

Using this scheme most NS are proxied through VALID entries. Other NS are forwarded during packet loss, retries for nonexistent IP, or someone hammering the proxy with forged messages ;) In the later case, we could use a min_retrans_timer option to limit the number of forwarded NS. A timer would ensure a minimum duration between each NS forwarded inwards.

**Comment by DanielAdolfsson** [comment]
I'm doing a rewrite of ndppd to make it more lightweight and make the code more maintainable. I'll take this into consideration for the upcoming version.

**Comment by john-sharratt** [comment]
I just noticed that I'd accidentally fixed this issue by implementing a "deadtime" setting (https://github.com/DanielAdolfsson/ndppd/pull/30) which is more inline with Daniels first comment in this thread.

On another note - just wanted to say that if you ask me the code is already quite easy to read and maintain - I found the fork I did quite pleasure to work on today and it only took me a day, so compliments to the original writer is due.

Cheers
John

**Comment by DanielAdolfsson** [comment]
This was ported as `invalid-ttl` to 1.0-devel.
