### ISSUE TITLE
Option to not retrieve routes

### ISSUE THREAD

**Issue by vincentbernat** [DanielAdolfsson/ndppd#20]
Hey!

When not using any rule with "auto", the route cache is useless. If the router has a very large route table, we are wasting memory. Ideally, ndppd shouldn't fetch routes if no "auto" rule is present. Alternatively, an option to let the user disable it would be great.

Thanks.

**Comment by DanielAdolfsson** [comment]
Disable the cache, you mean?

**Comment by DanielAdolfsson** [comment]
Nevermind, I understand what you mean now. I'll look into it.

**Comment by DanielAdolfsson** [comment]
Untested for now, but routes will only be loaded if at least one rule is configured with "auto".
