### ISSUE TITLE
ndppd.service: (error) Shutting down....

### ISSUE THREAD

**Issue by fansari** [DanielAdolfsson/ndppd#21]
I tried this simple config for an ndppd.service on Centos7 and Fedora 25.

[Unit]
Description=NDP proxy daemon
After=network.target

[Service]
Type=simple
ExecStart=/usr/local/sbin/ndppd -d
KillSignal=SIGINT
Restart=on-failure

[Install]
WantedBy=basic.target

In both cases this is what happens when I start with "systemctl start ndppd":

-- Logs begin at Sat 2017-03-25 19:58:23 CET, end at Thu 2017-04-06 20:15:03 CEST. --
Apr 06 20:06:29 bat.localdomain systemd[1]: Started NDP proxy daemon.
Apr 06 20:06:29 bat.localdomain ndppd[6220]: (notice) ndppd (NDP Proxy Daemon) version 0.2.4
Apr 06 20:06:29 bat.localdomain ndppd[6220]: (notice) Using configuration file '/etc/ndppd.conf'
Apr 06 20:06:29 bat.localdomain ndppd[6221]: (error) Shutting down...
Apr 06 20:06:29 bat.localdomain ndppd[6221]: (notice) Bye

On the other hand: starting "ndppd -d" from command line works without problems.

What can be the reason for this behaviour?

**Comment by DanielAdolfsson** [comment]
Did you figure this out?

**Comment by florianl** [comment]
@meeuw provided an improved systemd file in https://github.com/DanielAdolfsson/ndppd/pull/12

**Comment by fansari** [comment]
orry, but it still does not work.
```
[root@frank-router ~]# journalctl -f -u ndppd
-- Logs begin at Mon 2017-05-15 13:36:10 CEST. --
May 17 10:09:58 frank-router.localdomain ndppd[7874]: (notice) ndppd (NDP Proxy Daemon) version 0.2.4
May 17 10:09:58 frank-router.localdomain ndppd[7874]: (notice) Using configuration file '/etc/ndppd.conf'
May 17 10:09:58 frank-router.localdomain ndppd[7875]: (error) Shutting down...
May 17 10:09:58 frank-router.localdomain ndppd[7875]: (notice) Bye
May 17 10:10:16 frank-router.localdomain systemd[1]: Starting NDP Proxy Daemon...
May 17 10:10:16 frank-router.localdomain ndppd[7913]: (notice) ndppd (NDP Proxy Daemon) version 0.2.4
May 17 10:10:16 frank-router.localdomain ndppd[7913]: (notice) Using configuration file '/etc/ndppd.conf'
May 17 10:10:16 frank-router.localdomain systemd[1]: PID file /var/run/ndppd/ndppd.pid not readable (yet?) after start.
May 17 10:11:21 frank-router.localdomain systemd[1]: [/etc/systemd/system/ndppd.service:1] Assignment outside of section. Ignoring.
May 17 10:11:21 frank-router.localdomain systemd[1]: [/etc/systemd/system/ndppd.service:2] Assignment outside of section. Ignoring.
```

**Comment by DanielAdolfsson** [comment]
Great! Closing this issue.
