### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by DanielAdolfsson** [DanielAdolfsson/ndppd#25]
Things I would like to do:

- Refactor the code to use a later C++ version (maybe auto etc.)
- CMakeFile instead of a regular Makefile
- Switch from the own pointer implementation to std::shared_ptr
- Some general cleanup
- Better "flow" in the code, make it easier to follow

If anyone have any input on this, just add a comment.

**Comment by DanielAdolfsson** [comment]
Maybe the focus should be to make it as lightweight as possible, to make it kinder to embedded systems.

* Better memory management (freelists and such).
* Ability to set max number of sessions and/or memory limit.

**Comment by nihilus** [comment]
Maybe rewrite it in C?

**Comment by DanielAdolfsson** [comment]
Closing this as 1.0-devel branch is up now.
