### ISSUE TITLE
Weird issue - works, but only for a few seconds?

### ISSUE THREAD

**Issue by bcacbe** [DanielAdolfsson/ndppd#26]
Not sure if this is an ndppd issue or something else. I'm using ndppd on an openvpn tunnel so that the LAN on the client side can have IPv6 addresses. I have a /64.

To get it working, on the client side I need to ping the ipv6 address setup on the server side. Once that is done, I can then ping the internet from the client side. The problem is this stops working after a few seconds and until I place a ping back on the server ipv6 address. 

Without ndppd it can never ping the Internet from the client side. So i'm making progress, but something is  still wrong. If someone could point me in the right direction it would be appreciated.

**Comment by DanielAdolfsson** [comment]
Could you show me your config file?

**Comment by bcacbe** [comment]
`
proxy eth0 {
router yes
        rule 2605:xxxx:x:xx::a/64 {
static
        }
}
`

**Comment by bcacbe** [comment]
I have been following the config at the blog below. But still had the same issue.

http://blog.iopsl.com/ndppd-on-vultr-to-enable-fully-routed-64-for-ipv6/

**Comment by DanielAdolfsson** [comment]
What would happen if you replaced static with `iface eth1` (replacing eth1 with whatever your internal interface is)?

**Comment by bcacbe** [comment]
Doesn't work at all with iface tun0

**Comment by DanielAdolfsson** [comment]
Are you able to connect to the client from the server before the client pings it? Feels a bit like the client isn't responding to neighbor solicitation messages properly, and you're only able to connect briefly because the client is sending an unsolicited neighbor advertisement to the server.

**Comment by DanielAdolfsson** [comment]
And by connecting, I mean over IPv6 obviously :)

**Comment by bcacbe** [comment]
No, can not ping from the server to the client ipv6 address. Only the client can ping the server.

**Comment by bcacbe** [comment]
I don't have any firewalls running. Could the client side need a route added?

**Comment by DanielAdolfsson** [comment]
It's possible that it could be a routing problem, but from the server side.
What does your ` ip -6 route show dev tap0` say?

**Comment by bcacbe** [comment]
I'm using tun. Here is the output of "ip -6 route show dev tun0"

2605:xxxx:x:32::/64  proto kernel  metric 256
2605:xxxx:x:32::/64 via 2605:9300:2:32::1  metric 1024

**Comment by DanielAdolfsson** [comment]
Alright, lastly, would you like to provide the `ip -6 addr` list as well?
It's possible that the server is simply not sending the solicitation message properly.

**Comment by DanielAdolfsson** [comment]
Oh, and the routing table you provided, that was *on* the server right?

**Comment by bcacbe** [comment]
Yes, that was from the server. Here is the ip -6 addr output

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,ALLMULTI,UP,LOWER_UP> mtu 1500 qlen 1000
    inet6 2605:xxxx:2:32::a:100/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::216:3eff:feed:7/64 scope link
       valid_lft forever preferred_lft forever
3: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qlen 100
    inet6 2605:xxxx:2:32::a:1/64 scope global
       valid_lft forever preferred_lft forever

**Comment by DanielAdolfsson** [comment]
It looks to me like you're using a /64 prefix on eth0.
Do you have a route on eth0 similar to `2605:xxxx:2:32::/64`?

**Comment by bcacbe** [comment]
Yes it appears that way. Here is the etho output.

2605:9300:2:32::/64  proto kernel  metric 256
fe80::/64  proto kernel  metric 256
default via 2605:9300:2:32::1  metric 1024

**Comment by DanielAdolfsson** [comment]
I would remove the first route, and add one specifically for xxxx:xxxx:2:32::1
ip -6 route add xxxx:xxxx:2:32::1 dev eth0
ip -6 route del xxxx:xxxx:2:32::/64 dev eth0

See if that works

**Comment by bcacbe** [comment]
I think that worked. I rebooted both sides and when it came up i was able to ping facebook over ipv6 on the client without having to ping the server ipv6 address. I'll run a few more tests here, but I think that cured the issue. Very much appreciate your help.

**Comment by DanielAdolfsson** [comment]
Was it the routes, or did it start working anyway?

I'm glad you got it working!

**Comment by bcacbe** [comment]
Yes, was the routes. Thanks.
