### ISSUE TITLE
can ndppd handle more than one hop?

### ISSUE THREAD

**Issue by bcacbe** [DanielAdolfsson/ndppd#27]
Will ndppd handle multiple hops using a /64?

My setup is (server---openvpn tunnel tun---client/router/gateway---wifi/lan clients)

I have ndppd running on the server and client side server. We got the server-client ipv6 working on both sides, but i'm having doubts whether the wifi/lan devices behind the client side server will work?

**Comment by DanielAdolfsson** [comment]
That should work. Just make sure you set up routing properly, and install ndppd on both servers.
Does all the nodes (server, gateway, and clients) use the same /64 subnet?

**Comment by bcacbe** [comment]
Yes, the same /64. i'm guessing the routes are an issue. On the client side, lan clients are not able to ping anything which is odd. I have them being assigned an ipv6 via dnsmasq.

**Comment by bcacbe** [comment]
Placing the interface that handles the lan clients (eth1) on the client side in bridge mode is allowing the lan clients to ping the client side server ipv6 addresses. But won't go past that point.

I'm thinking it's a routing table issue at this point.

2605:9300:2:32::/64 dev br0  proto kernel  metric 256
2605:9300:2:32::/64 dev tun0  proto kernel  metric 256
2000::/3 dev tun0  metric 1024
fe80::/64 dev br0  proto kernel  metric 256
fe80::/64 dev eth0  proto kernel  metric 256

**Comment by DanielAdolfsson** [comment]
Will you be using all the IPs for clients? If not, I suggest you dedicate a subnet to them.
The key point is so make sure there is no ambiguous path to your destination.

In this example, the clients use 2605:9300:2:32:1::/80

Server:
2605:9300:2:32:0::1
Route to clients: 2605:9300:2:32:1::/80 dev tun0

ClientServer:
2605:9300:2:32:1::1
Route to clients: 2605:9300:2:32:1::/80 dev br0
Route to server: 2605:9300:2:32:0::/80 dev tun0
Default via 2605:9300:2:32:0::1

Client 1:
IP: 2605:9300:2:32:1::10
Route: 2605:9300:2:32:1::/80 dev eth0
Default via 2605:9300:2:32:1::1

Obviously, ndppd need to be configured in a similar fashion.

**Comment by bcacbe** [comment]
Hmm, I only have the /64 block of 2605:9300:2:32:a::/64 so i don't think that will work as those IP's are outside my block.

**Comment by DanielAdolfsson** [comment]
The examples I gave you fit inside your /64 block.

**Comment by bcacbe** [comment]
Sorry for any confusion. My provider assigned me "2605:9300:2:32::a", "netmask /64" and gateway "2605:9300:2:32::1". Wouldn't "2605:9300:2:32:0::" and "2605:9300:2:32:1::" be outside of the range that I can use?

**Comment by DanielAdolfsson** [comment]
`2605:9300:2:32::a` is only one IPv6 address, and is not enough if you want to connect other machines.
Would indeed be strange if you only got one (/128) address assigned.

Are you sure you don't have the whole 2605:9300:2:32::/64 range?

**Comment by bcacbe** [comment]
Good catch. I sent them a ticket for clarification.
