### ISSUE TITLE
NS routing

### ISSUE THREAD

**Issue by dulemis** [DanielAdolfsson/ndppd#29]
Hi!

Great software. In my case my ISP gives me a fully routed /64 (6rd-tunnel), so I don't need any proxyin on the upstream interface, however I do need proxyin on my local gateway (ie lan 1 on eth1, lan2 on eth2) and to not brake SLAAC a /64 cannot be split. So it would be nice if ndppd could be improved by some form of dynamic routing logic, for example forward NS from eth1 to eth2 and create an "ip route" pointing at eth2 (as long as the NS is valid).
The reason for this is the gateway can't have two identical routes for the same prefix on both eth1 and eth2, well it can but it conflicts and doesnt work so great. If your software could add individual routes for a single host, depending on which interface it is located, that would be just great.

**Comment by DarthGandalf** [comment]
I see you've discovered [ndprbrd](https://github.com/google/ndprbrd) already :-)
But if such functionality is included into ndppd itself, this would probably be easier to setup than 2 separate daemons.

**Comment by dulemis** [comment]
Yes, I have! :)
And yes, I do agree.

**Comment by DanielAdolfsson** [comment]
Fixed in 1.0-devel
