### ISSUE TITLE
Autowire: Support policy based routing

### ISSUE THREAD

**Issue by DarthGandalf** [DanielAdolfsson/ndppd#33]
Currently `ip route` command is called without specifying `table`, so the table defaults to `main`.
It assumes that this table is used, but the list of actual tables used depends on `ip rule show`.

Need to add a configuration parameter, which routing table to update.

Moved from google/ndprbrd#6
@john-sharratt FYI

**Comment by DanielAdolfsson** [comment]
In 1.0-devel, you can now specify `table` in a rule section.
