### ISSUE TITLE
install instructions broken because nd-proxy isn't built by `make all`

### ISSUE THREAD

**Issue by bgentry** [DanielAdolfsson/ndppd#35]
Hi there, these are the install instructions in the readme:

```bash
make all && make install
```

However, `make all` does not build the `nd-proxy` executable, which `make install` attempts to copy. Therefore `make install` fails unless you also run `make nd-proxy`.

I was going to PR a fix for this, but wasn't sure if you'd prefer to add `nd-proxy` to `make all`, or if you'd prefer to remove the `cp nd-proxy ...` from `make install`. Presumably the former? Happy to PR if you want to confirm which approach you want to see.

Cheers :v:

**Comment by DanielAdolfsson** [comment]
nd-proxy is something that should probably be removed altogether
