### ISSUE TITLE
ndppd as daemon vs. foreground

### ISSUE THREAD

**Issue by sudhagarc** [DanielAdolfsson/ndppd#39]
ndppd works fine when ran in foreground mode, however when I make ndppd run in daemon mode, then it doens't seem to work. After several tries, then daemon mode works, but it's unclear whether it will continue to run that way. Both foreground and daemon is run from same user with same configuration file.

I'm using the latest code from master branch.

Does ndppd require any special configuration to run reliably in daemon mode? Any ideas on how to make this work?

My requirement is to have the daemon started automatically when the machine boots and provide ndp proxy service.

**Comment by fansari** [comment]
For me it does not work anymore at all - neither in foreground nor in background.
My scenario is very simple. I just have a KVM guest which should be able to communicate with the outer world via IPv6.

**Comment by torbennehmer** [comment]
Same effect as @sudhagarc  her as well, running latest GIT on Debian jessie. 

@DanielAdolfsson Any ideas, what this could be?

**Comment by torbennehmer** [comment]
@DanielAdolfsson What I can see here is, that the interface doesn't gain the ALLMULTI flag. Starting without Daemonizing everything is fine:
2: eth0: <BROADCAST,MULTICAST,ALLMULTI,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000

but with Deamon, the interface remains as-is:
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000

**Comment by DanielAdolfsson** [comment]
It's likely related to commit https://github.com/DanielAdolfsson/ndppd/commit/2f10118a5c8976021fd27496bc60f431b9154af6. After the fork, the parent will probably restore ALLMULTI to it's previous state. Configuration should probably be deferred until after daemonization. See if moving ndppd.cc line 354-355 to 363 (thus placing the configuration lafter daemonize()).

**Comment by torbennehmer** [comment]
@DanielAdolfsson: This actually does the trick. The interface stays in ALLMULTI now and the NDP requests are correctly answered. I've sent you a pull request for it (along with a second one with an init script for Debian).
