### ISSUE TITLE
Build error still occurs on Alpine Linux

### ISSUE THREAD

**Issue by lqf96** [DanielAdolfsson/ndppd#40]
I tried to build ndppd on Alpine Linux, but build error still occurs due to musl using a XSI-compliant `strerror_r` function. The feature detection macro failed to detect the right version because once I removed the macro the program compiled without any problems. It may be better to fix the problem using function overloading as suggested by [this](https://github.com/chriskohlhoff/asio/commit/443bc17d13eb5e37de780ea6e23157493cf7b3b9) commit.

Also there seems to be a bracket missing at the end of line 88 in `logger.cc`.

**Comment by navossoc** [comment]
Yes, you are right, it was missing a parentheses there. Also the macro was not being triggered by some other header.

I think this should fix the problem, please take a look:
https://github.com/DanielAdolfsson/ndppd/compare/master...navossoc:master

[]'s

**Comment by navossoc** [comment]
Hi, I'm testing it since my last post here...

Although the binary works in alpine, it seems that there are more differences between `musl` and` glibc`.

Recently I noticed a difference in the behavior of this snippet of code:

```cpp
#include <iostream>
#include <fstream>
int main()
{
    std::ifstream f("doesn't exist");
    try {
        f.exceptions(f.failbit);
    } catch (const std::ios_base::failure& e)
    {
        std::cout << "Caught an ios_base::failure.\n"
                  << "Explanatory string: " << e.what() << '\n'
                  << "Error code: " << e.code() << '\n';
    }
}
```
Source: https://en.cppreference.com/w/cpp/io/ios_base/failure

On alpine:
```
~ # g++ test1.cpp -o test1 && ./test1
terminate called after throwing an instance of 'std::ios_base::failure'
  what():  basic_ios::clear
Aborted
```

On debian:
```
root@56f133be9890:~# g++ test1.cpp -o test1 && ./test1
Caught an ios_base::failure.
Explanatory string: basic_ios::clear: iostream error
Error code: iostream:1
```

Maybe there are more cases like this, but overall `npddp` works fine.

**Comment by DanielAdolfsson** [comment]
Probably not relevant anymore. We switch to C in 1.0-devel.
