### ISSUE TITLE
Source address used by ndppd may not be a neighbor address

### ISSUE THREAD

**Issue by vincentbernat** [DanielAdolfsson/ndppd#41]
Hello!

I am using ndppd on interfaces where I don't have anything else than a link-local address. Due to the scope rule, Linux won't use it when sending packets for a globally reachable address. It selects another address from another interface. The selected address is not in the same subnet as the target address. Some OS will refuse neighbor advertisements coming from a non-neighbor address. For example, in OpenBSD, I get:

    nd6_na_input: ND packet from non-neighbor

RFC 4861 doesn't say much except the source address should be "an address assigned to the interface from which the advertisement is sent." We could use the link-local address, hoping some OS won't be too picky about that or use a fake address (that could be specified in the configuration file). In both cases, `sendmsg()` cannot be used, which would make the change rather extensive.

**Comment by DanielAdolfsson** [comment]
This is fixed in 1.0-devel.
