### ISSUE TITLE
Fedora 28: ndppd does not work anymore

### ISSUE THREAD

**Issue by fansari** [DanielAdolfsson/ndppd#42]
Some time ago I noticed that ndppd has not effect anymore on my system (#38).

My /etc/ndppd.conf is like this:

```
route-ttl 30000
proxy wlp4s0 {
   router yes
   timeout 500   
   ttl 30000
    rule 2a02:xxxx:xxxx:xxxx::/64 {
          iface virbr0
   }
}
```
Both interfaces wlp4s0 and virbr0 have addresses from 2a02:xxxx:xxxx:xxxx::/64 range.

Also my kvm guest has an IP from this range.

When I do 

```
ip -6 neigh add proxy 2a02:xxxx:xxxx:xxxx dev wlp4s0
```
on my host system when the given IP is the IP of the kvm guest it works.

A simple test on the kvm guest ist to ping Google DNS:

```
ping6 2001:4860:4860::8888
```
But just starting the ndppd service on the host system does not make the ping work on the kvm guest.

**Comment by fansari** [comment]
Ah - now I see I opened #38 in January.

**Comment by torbennehmer** [comment]
Try using an explicit interface assignment to which the IP is sent to, I couldn't get a rule with auto mode in my system as well for reasons yet unknown.

**Comment by nihilus** [comment]
Actually got this issue as well, I think it has to do with ndppd being utterly broken and especially after the merge with the Google code.

**Comment by nihilus** [comment]
I suspect PR #30 is the culprit!

**Comment by nihilus** [comment]
Goes to show my issue was related to the upstream interface answering on NDP for ::/0. Alas this case cannot be handled by ndppd but the Linux kernel works well, so I switched to 6brd/6relayd.

**Comment by DanielAdolfsson** [comment]
Closing this as it might not be relevant for `1.0-devel`.
