### ISSUE TITLE
New release please?

### ISSUE THREAD

**Issue by stapelberg** [DanielAdolfsson/ndppd#46]
We just debugged network connectivity issues to be caused by #6 (lack of unicast solicitation support).

Unfortunately 0.2.5 (one commit behind the fix) is the latest version in Debian.

Could you please release a new version so that the fix can be made available to Debian users?

Thank you.

**Comment by DanielAdolfsson** [comment]
There will be no more release of 0.x, but I hope to get 1.0-devel ready soon.
