### ISSUE TITLE
feature: C only instance for embedded use.

### ISSUE THREAD

**Issue by nihilus** [DanielAdolfsson/ndppd#48]
Beats me that I need this code running on an environment without proper C++ support, it would be nice to have a C-only instance for this rather than rewriting the whole daemon.

**Comment by nihilus** [comment]
Or having to pull in uClibc++.

**Comment by nihilus** [comment]
Replacing the logger class and pidfile class vastly shrunk the size with over 30%

**Comment by DanielAdolfsson** [comment]
A complete rewrite of ndppd is in the making, and is C only. Not sure when it'll be ready, but soon I hope. Still a couple of features I'm working on backporting. A big difference both in terms of binary size, and in terms of memory usage.

**Comment by nihilus** [comment]
Cool!

**Comment by DanielAdolfsson** [comment]
Reopening this. Not fair to close it until the C version is released.

**Comment by DanielAdolfsson** [comment]
There is a branch for 1.0 now, but not ready yet. Closing this.
