### ISSUE TITLE
don't call system() for setting/getting routes etc

### ISSUE THREAD

**Issue by nihilus** [DanielAdolfsson/ndppd#49]
What is this "system(route_cmd.str().c_str());" , does that scale well on a busy system etc? You have a wrapper around netlink so I suggest using that.

Using system() is not only a bad practice but it can create issues with multi-threading etc.

**Comment by DanielAdolfsson** [comment]
I agree, and I've been considering using netlink for that instead- since we're using it now to monitor interfaces anyway. However, I don't really have much time to work on the issue at the moment, so we'll see when it will get fixed.

**Comment by nihilus** [comment]
Actually for getting ipv4 routes I've got some code. However what is this nd-proxy.c-stuff?

**Comment by nihilus** [comment]
I've already started the integration, so I will fix it sooner or later.

**Comment by DanielAdolfsson** [comment]
Fixed in 1.0-devel.
