### ISSUE TITLE
pid file is world writable

### ISSUE THREAD

**Issue by nirgal** [DanielAdolfsson/ndppd#56]
In Debian 10, the stop action of init.d doesn't work anymore because the pid file is 0666, and start-stop-daemon(8) refuses to handle that nasty permissions, since dpkg version 1.19.3.

So the daemon can't be stopped anymore, short of a kill.

Initially by reported by Fabrice Meyer at https://bugs.debian.org/942117

**Comment by chadek** [comment]
If you manually kill ndppd process you can't revive it either because of this issue. I think it should be a good idea to "take advantage" of this issue to include a systemd service

**Comment by nirgal** [comment]
You have to remove the pid file manually if you kill the service.

Having a systemd file is a nice optimization for people using systemd. But it won't do any good for other people. This needs to be fixed anyway.

**Comment by nirgal** [comment]
Here's a patch
[pid_perms.txt](https://github.com/DanielAdolfsson/ndppd/files/3720531/pid_perms.txt)

**Comment by chadek** [comment]
That was fast, thank you!

**Comment by nirgal** [comment]
I almost removed the -d & -p parameters from the init script, so that start-stop-daemon could handle the pid file creation and the daemonization by itself. That would do the trick.
Unfortunately, that would break the logger, and there is no option to enable syslog without the -d option. So it would be nice to have a separate option for enabling syslog, and possibly have -d implies that.

**Comment by DanielAdolfsson** [comment]
Fixed in 1.0-devel.
