### ISSUE TITLE
When using any mode, periodic packet loss/recovery

### ISSUE THREAD

**Issue by bradjones1** [DanielAdolfsson/ndppd#6]
Thanks very much for a super helpful library, though I am having some trouble with regular packet loss when using static mode, but also in auto and iface. I am trying to use ndppd in conjunction with Docker to avoid having to write specific proxy rules for every container as it's created. If I do manually create the proxy rules, though, they work as desired without any packet loss.

Below is an excerpt of syslog where requests for 2607:f0d0:1001:4a:dddd:242:ac11:6b are being proxied through ndppd - I note where the packet loss starts, and then where it resumes.
```
Jun 11 14:42:50 summit ndppd[6453]: (debug) iface::read() len=86
Jun 11 14:42:50 summit ndppd[6453]: (debug) iface::read_solicit() saddr=fe80::215:c7ff:fe32:a000, daddr=2607:f0d0:1001:4a:dddd:242:ac11:6b, len=86
Jun 11 14:42:51 summit ndppd[6453]: (debug) iface::read() len=86
Jun 11 14:42:51 summit ndppd[6453]: (debug) iface::read_solicit() saddr=fe80::215:c7ff:fe32:a000, daddr=2607:f0d0:1001:4a:dddd:242:ac11:6b, len=86
Jun 11 14:42:52 summit ndppd[6453]: (debug) iface::read() len=86
Jun 11 14:42:52 summit ndppd[6453]: (debug) iface::read_solicit() saddr=fe80::215:c7ff:fe32:a000, daddr=2607:f0d0:1001:4a:dddd:242:ac11:6b, len=86

DROPS HERE

Jun 11 14:43:01 summit ndppd[6453]: (debug) iface::read() len=86
Jun 11 14:43:01 summit ndppd[6453]: (debug) iface::read_solicit() saddr=fe80::215:c7ff:fe32:a000, daddr=2607:f0d0:1001:4a::1:1, len=86
Jun 11 14:43:01 summit ndppd[6453]: (debug) iface::read() len=24
Jun 11 14:43:01 summit ndppd[6453]: (debug) iface::read_advert() saddr=2607:f0d0:1001:4a:c89e:a601::, taddr=2607:f0d0:1001:4a::1, len=24
Jun 11 14:43:06 summit ndppd[6453]: (debug) iface::read() len=86
Jun 11 14:43:06 summit ndppd[6453]: (debug) iface::read_solicit() saddr=fe80::215:c7ff:fe32:a000, daddr=ff02::1:ff11:6b, len=86
Jun 11 14:43:06 summit ndppd[6453]: (debug) proxy::handle_solicit() saddr=fe80::215:c7ff:fe32:a000, taddr=2607:f0d0:1001:4a:dddd:242:ac11:6b
Jun 11 14:43:06 summit ndppd[6453]: (debug) checking 2607:f0d0:1001:4a:dddd::/80 against 2607:f0d0:1001:4a:dddd:242:ac11:6b
Jun 11 14:43:06 summit ndppd[6453]: (debug) session::create() pr=1a60190, saddr=fe80::215:c7ff:fe32:a000, daddr=ff02::1:ff11:6b, taddr=2607:f0d0:1001:4a:dddd:242:ac11:6b =1a637f0
Jun 11 14:43:06 summit ndppd[6453]: (debug) iface::write_advert() daddr=fe80::215:c7ff:fe32:a000, taddr=2607:f0d0:1001:4a:dddd:242:ac11:6b
Jun 11 14:43:06 summit ndppd[6453]: (debug) iface::write() daddr=fe80::215:c7ff:fe32:a000, len=32
Jun 11 14:43:06 summit ndppd[6453]: (debug) session::~session() this=1a637f0
Jun 11 14:43:06 summit ndppd[6453]: (debug) iface::read() len=86
Jun 11 14:43:06 summit ndppd[6453]: (debug) iface::read_solicit() saddr=fe80::215:c7ff:fe32:a000, daddr=fe80::225:90ff:fe2e:1ea1, len=86

RESTARTS HERE
```

There is an ipv6 route on the machine:
`2607:f0d0:1001:4a:dddd::/80 dev docker0  metric 1024`
And here is the ndppd.conf:
```
proxy eth1 {
  rule 2607:f0d0:1001:4a:dddd::/80 {
    static
  }
}
```

The device with the link-local address `fe80::215:c7ff:fe32:a000` appears to be involved, though I for the life of me can't determine what interface it might be set on. On the docker host it doesn't appear in a list from `ip -6 addr show`.

Any thoughts you can provide would be much appreciated and thanks again!

**Comment by ross211** [comment]
I have observed similar behaviour. Doing tcpdumps while it's occurring shows that it's not replying to the NDP requests until it eventually does which is when things start working again. Reducing route-ttl and ttl down to 1 second seems to hide the problem, I think for some reason the caching is preventing it from sending responses.

**Comment by DanielAdolfsson** [comment]
Hey, sorry about the slow response!

I don't get what you mean by ***DROPS HERE*** and ***RESTARTS HERE***. Below ***DROPS HERE*** there seem to be some kind of ndppd response; is that when ndppd did work as expected?

**Comment by bradjones1** [comment]
The DROP/RESTART annotations refer to when pings to the address in question stop getting a reply.

**Comment by bradjones1** [comment]
Any thoughts on this? Thanks for your continued development on this project.

**Comment by bradjones1** [comment]
FWIW, I am beginning to think this may be less a ndppd issue per se but something about NDP proxy entries in general; I've turned off ndppd and added a few manual entries (with `ip -6 neigh add proxy xxx:xxx dev eth1` and the packet loss is similar... though with no corresponding syslog entries, of course.

**Comment by Kahn** [comment]
@bradjones1 have you gotten any further with this?

**Comment by bradjones1** [comment]
@Kahn Unfortunately, no. I am hosting at SoftLayer, and while they're generally very good with support, after a long back-and-forth they basically said they won't support NDP for IPv6. So I will likely need to just order a subnet of addresses and have them routed directly to the machine, instead of my VLAN.

So while that doesn't rule out a problem with the software, per se, it's likely the problem lies on the network side in my particular case.

**Comment by nirgal** [comment]
Does forcing the interface in promiscuous mode help?
See issue #13

**Comment by DanielAdolfsson** [comment]
With the latest changes, do you still have the same problem?

**Comment by bradjones1** [comment]
I can see the interface going into `ALLMULTI`, but it doesn't seem to fix the problem. I also tried setting it manually prior to launching the program, and still the same. Here's [a log](https://github.com/DanielAdolfsson/ndppd/files/265233/ndppd.log.txt) with an annotation when the ping starts to hang, and then resumes. Thanks for any help.

**Comment by DanielAdolfsson** [comment]
I think I have identified a problem with the interface being closed and the routing table being re-read.
This, however, can only affect "auto" mode.

Does "static" and "iface" drop packets as well?

**Comment by bradjones1** [comment]
Thanks
[ndppd.log2.txt](https://github.com/DanielAdolfsson/ndppd/files/266999/ndppd.log2.txt)
 for the help as always. Attached is an updated log - the blank lines are where the ping drops packets. `2607:f0d0:1001:4a::1` is the host which has its address specified straight in the interfaces file; `2607:f0d0:1001:4a:dddd:242:ac11:38b` is the host on the Docker bridge.

**Comment by DanielAdolfsson** [comment]
There seemed to be a couple of issues;

The first one being the interface being freed when the routing table is re-read, and the second one being that ndppd didn't (up until now) support unicast solicitation messages.

The latest commit should fix the first issue, and implement experimental support for unicast messages.

**Comment by bradjones1** [comment]
I'm going to (very tentatively!) say this has resolved the problem here... while in my environment it takes a few seconds for the routing to get set up and for packets to initially return during a ping (which appears to just be my datacenter provider's environment) once that happens, I do not get the intermittent packet drops as before. I usually only had to wait 30-60 seconds to see this issue, and now I am getting long runs with no packet loss. Going to run it for a few hours over lunch here and see if I can catch any weirdness, but I think you've squashed it! Thanks so much! Let me know how I can buy you a :coffee: or :beer:.
