### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by dagmoller** [DanielAdolfsson/ndppd#61]
src/iface.c: In function ‘nd_iface_send_ns’:
src/iface.c:624:5: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
     *(uint32_t *)&ll_mcast.u8[2] = tgt->u32[3];
     ^
cc1: all warnings being treated as errors
Makefile:35: recipe for target 'src/iface.o' failed
make: *** [src/iface.o] Error 1

**Comment by DanielAdolfsson** [comment]
Which compiler + version are you using?

**Comment by DanielAdolfsson** [comment]
This should be fixed in commit https://github.com/DanielAdolfsson/ndppd/commit/c99eb16373fef106370c561d471f1c011d1f9d91
