### ISSUE TITLE
Adding an option to use the target IP as source IP of the advert

### ISSUE THREAD

**Issue by briaeros** [DanielAdolfsson/ndppd#64]
Advert on Linux (at least a 5.4.0-4-amd64 on debian) behaves differently if it uses a proxy neighbour  ( ip -6 neigh add proxy ) (case A) or responds for an interface it owns (case B).
ndppd mimic the proxy neighbour.

I'd love to have an option to make ndppd behave as if we have interface with the IP.

The only difference is the source address of the advert. 
for case A(the proxy) : the source IP is the fe80:: address of the output interface
for case B: the source IP is the target address.

For information , on a provider where neigbour proxy doesn't work, I've validate the usage with sylkie (https://github.com/dlrobertson/sylkie) with the command line 
sylkie na -i ens3 --dst-mac 0c:c4:7a:00:00:fa --dst-ip fe80::ec4:7aff:fe00:00fa --src-ip 2a00:0000:e:1::4 --target-ip  2a00:0000:e:1::4  --repeat -1 --timeout 10

I could code a little, so I could try to do a PR, but I'd rather have expert opinions on how integrate the low-level network code before beginning :)

**Comment by DanielAdolfsson** [comment]
Let me get this right, are you saying ndppd is using the wrong source address when it sends the advert? It's supposed to use the IP of the outgoing interface, not the target address.

*Edit* Nevermind, I think I see what you mean. _ndppd_ follows **RFC 4861**, and it clearly states that it's supposed to be using the address of the outgoing interface when sending NA. _ndppd_ does not implement **RFC 4389** (ND proxy), and not even that RFC allows for any other source address than the address of the outgoing interface.

I'm going to have to investigate and see what you mean.

**Comment by DanielAdolfsson** [comment]
If you're able, maybe you can attach some logs (tcpdump, ndppd, etc)?

**Comment by briaeros** [comment]
Hi,
Sorry for the delay, I did a bit of test to extract the pcap.
I do agree with the RFC, but my request could be see as an option to "make believe" (for the external router) that we've got this ip on our interface (even if it is on another network) :).

On my settings, ndppd seems a little susceptible, and when I tried to make a pcap I didn't see any NA this time, even though I do not change anything to the configuration with my previous tests.

I've attached 3 pcap.
- neighbour_sollication_ok : A new IP on my physical interface. We see no trouble here
- neighbour_sollicitation_ko_proxy : A response of the neighbour sollicitation with ip -6 neigh add proxy 
- neighbour_sollicitation_brute_proxy : I send a crafted neighbour advertisement every 2 seconds with sylkie(so there are no synchronization with the neighbour sollicitation, and it triggers some bans on the router ^^').

Edit : Adding two more files for the use case with ndppd : nddpd.log.gz, which show the nddpd output, and ndppd.pcap.gz wich is the corresponding network trace.
As said: ndppd works as the ndp proxy.


[neighbour_sollication_brute_proxy.pcap.gz](https://github.com/DanielAdolfsson/ndppd/files/4764084/neighbour_sollication_brute_proxy.pcap.gz)
[neighbour_sollication_ko_proxy.pcap.gz](https://github.com/DanielAdolfsson/ndppd/files/4764085/neighbour_sollication_ko_proxy.pcap.gz)
[neighbour_sollication_ok.pcap.gz](https://github.com/DanielAdolfsson/ndppd/files/4764086/neighbour_sollication_ok.pcap.gz)
[ko_ndppd.pcap.gz](https://github.com/DanielAdolfsson/ndppd/files/4767321/ko_ndppd.pcap.gz)
[ndppd.log.gz](https://github.com/DanielAdolfsson/ndppd/files/4767322/ndppd.log.gz)

**Comment by DanielAdolfsson** [comment]
Yes it would seem ndppd 0.x and the kernel behaves the way they should, that is according to the ND Proxy RFC. However, I see now that 1.0-devel is actually "spoofing" the IP address this way, unintentionally (setting source address to the target address). You should check it out.

As ndppd does not follow **RFC 4389** it might be possible to leave it as it is, for now, or at least add it as an option. 

0.x uses another method (through a ICMPv6 socket) for sending these messages that does not allow altering the source address, so this won't be added to 0.x. 1.0-devel, however, forges these messages by itself, allowing ndppd to "spoof" the source address.

I'll leave it in 1.0-devel for now.

**Comment by briaeros** [comment]
Hi,

Sorry for the long delay.
The devel version works great for me,so I will close this issues :)
It segfault some times (nothing that systemd could not handle:) ).
I will try to reproduce and investigate the segfault, and will open a new issue and/or PR if I find the culprit line or a reproducing method;)

Thanks a lot for all your work :)
