### ISSUE TITLE
ndppd doesn't work on a minimized server, what? 4vps

### ISSUE THREAD

**Issue by doroved** [DanielAdolfsson/ndppd#83]
I am using a virtual server https://4vps.su on Ubuntu 22.04
They provide IPv6 /64

I configure ndppd according to the manual from this repository https://github.com/zu1k/http-proxy-ipv6-pool.
Let me tell you right away that on **Vultr** virtual servers, everything works fine and there are no problems.

Let's start configuring...

1. When logging into the server we get this notification that the system has been minimized. I tried `unminimize` - it didn't help.
<img width="626" alt="image" src="https://github.com/DanielAdolfsson/ndppd/assets/30116541/d2a3e3dd-089f-4792-a6a3-5ae5758045ab">

2. Get your IPv6 subnet prefix, for me is `2a05:541:112:45::/64`.
```bash
ip -6 a
```
<img width="592" alt="image" src="https://github.com/DanielAdolfsson/ndppd/assets/30116541/6c707236-9d72-4fbe-939f-ee269c2b875e">

3. Add route via default internet interface
```bash
ip route add local 2a05:541:112:45::/64 dev ens3
```

4. Open `ip_nonlocal_bind` for binding any IP address:
```bash
sysctl net.ipv6.ip_nonlocal_bind=1
```
<img width="415" alt="image" src="https://github.com/DanielAdolfsson/ndppd/assets/30116541/986197f1-d944-4d78-80fd-c96fff323114">

5. For IPv6 NDP, install ndppd
```bash
apt-get install ndppd
```

Output
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  ndppd
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 65.2 kB of archives.
After this operation, 200 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 ndppd amd64 0.2.5-6build1 [65.2 kB]
Fetched 65.2 kB in 0s (359 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package ndppd.
(Reading database ... 93137 files and directories currently installed.)
Preparing to unpack .../ndppd_0.2.5-6build1_amd64.deb ...
Unpacking ndppd (0.2.5-6build1) ...
Setting up ndppd (0.2.5-6build1) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78.)
debconf: falling back to frontend: Readline
Scanning processes...
Scanning linux images...

Running kernel seems to be up-to-date.

No services need to be restarted.

No containers need to be restarted.

No user sessions are running outdated binaries.

No VM guests are running outdated hypervisor (qemu) binaries on this host.
```

6. Create `/etc/ndppd.conf`
```bash
nano /etc/ndppd.conf
```

7. Then edit `/etc/ndppd.conf`
```
route-ttl 30000

proxy ens3 {
    router no
    timeout 500
    ttl 30000

    rule 2a05:541:112:45::/64 {
        static
    }
}
```

8. Reboot ndppd and check the status
```bash
systemctl restart ndppd && systemctl status ndppd
```
<img width="940" alt="image" src="https://github.com/DanielAdolfsson/ndppd/assets/30116541/68f1a48a-728e-4803-ada1-a479047be407">

9. Now you can test by using curl
```bash
curl --interface 2a05:541:112:45::1 ifconfig.co
```
<img width="702" alt="image" src="https://github.com/DanielAdolfsson/ndppd/assets/30116541/6065e8c7-35c5-4a8b-b7dd-d488b06b5e9f">

**Question:** what might be missing on the current minimized server for ndppd to work correctly?

@DanielAdolfsson I am willing to give you access to the new server so you can investigate the problem. Let me know and I will email you the accesses) I hope for your help, as I have not found any information on this problem in search engines.

**Comment by DanielAdolfsson** [comment]
I'm not so sure that the system being "minimized"  (essentially reduced number of packages) is the reason why it's not working. 4vps is another provider, no? Have you been able to set up a working IPv6 configuration without ndppd, first?

**Comment by doroved** [comment]
> I'm not so sure that the system being "minimized" (essentially reduced number of packages) is the reason why it's not working. 4vps is another provider, no? Have you been able to set up a working IPv6 configuration without ndppd, first?

4vps is not the only place where ndppd doesn't work.
Here is the IPv6 setup without ndppd, everything works fine.

Add the address "2a05:541:104:72::f" to interface "ens3".
```
ip -6 addr add 2a05:541:104:72::f dev ens3
```
Open the kernel parameter configuration file
```
nano /etc/sysctl.conf
```
Add to the end of the file
```
net.ipv6.conf.ens3.proxy_ndp = 1
net.ipv6.ip_nonlocal_bind = 1
net.ipv6.conf.default.forwarding = 1
```
Load the modified kernel settings
```
sysctl -p
```

IPv6 information
```
ip -6 a && ip route show table all && cat /etc/network/interfaces
```
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 state UNKNOWN qlen 1000
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 2a05:541:104:72::f/128 scope global
       valid_lft forever preferred_lft forever
    inet6 2a05:541:104:72::1/48 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:fe1f:e10a/64 scope link
       valid_lft forever preferred_lft forever
default via 45.95.233.1 dev ens3 onlink
45.95.233.0/24 dev ens3 proto kernel scope link src 45.95.233.137
local 45.95.233.137 dev ens3 table local proto kernel scope host src 45.95.233.137
broadcast 45.95.233.255 dev ens3 table local proto kernel scope link src 45.95.233.137
local 127.0.0.0/8 dev lo table local proto kernel scope host src 127.0.0.1
local 127.0.0.1 dev lo table local proto kernel scope host src 127.0.0.1
broadcast 127.255.255.255 dev lo table local proto kernel scope link src 127.0.0.1
::1 dev lo proto kernel metric 256 pref medium
2a05:541:104:72::f dev ens3 proto kernel metric 256 pref medium
2a05:541:104::/48 dev ens3 proto kernel metric 256 pref medium
fe80::/64 dev ens3 proto kernel metric 256 pref medium
default via 2a05:541:104::1 dev ens3 metric 1024 onlink pref medium
local ::1 dev lo table local proto kernel metric 0 pref medium
local 2a05:541:104:72::1 dev ens3 table local proto kernel metric 0 pref medium
local 2a05:541:104:72::f dev ens3 table local proto kernel metric 0 pref medium
local fe80::5054:ff:fe1f:e10a dev ens3 table local proto kernel metric 0 pref medium
multicast ff00::/8 dev ens3 table local proto kernel metric 256 pref medium
# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto ens3
iface ens3 inet static
    address   45.95.233.137
    netmask   255.255.255.0
    gateway   45.95.233.1
    hwaddress ether 52:54:00:1F:E1:0A
    dns-nameservers 1.1.1.1 8.8.8.8
iface ens3 inet6 static
    address   2a05:541:104:72::1
    netmask   48
    gateway   2a05:541:104::1
    dns-nameservers 1.1.1.1 8.8.8.8
```

Checking
<img width="408" alt="image" src="https://github.com/DanielAdolfsson/ndppd/assets/30116541/36e3efc5-fb2a-4c4d-bd5b-e2711302adb1">

I think it would be a great solution if you let me send you access to the server (I'll order a clean, new server for you), that way we can identify and solve the problem much faster.

**Comment by doroved** [comment]
@DanielAdolfsson What do you think?

**Comment by DanielAdolfsson** [comment]
Hello, sorry about the late reply. 
I can't promise I will be able to help the next couple of weeks, as there is a lot of stuff on my plate atm, but should you still need assistance after new year I might be able to help. Sorry about that!

**Comment by doroved** [comment]
> Hello, sorry about the late reply. I can't promise I will be able to help the next couple of weeks, as there is a lot of stuff on my plate atm, but should you still need assistance after new year I might be able to help. Sorry about that!

Hi. Do you have time now to help with this problem?) Can I email you the access to the server?)

**Comment by doroved** [comment]
@DanielAdolfsson hi, ping)

**Comment by doroved** [comment]
@DanielAdolfsson hi, ping2)

**Comment by DanielAdolfsson** [comment]
Send me a mail directly and we'll take it from there;  daniel -at- ashen.se.
No need to spam the issues with support talk :)
