### ISSUE TITLE
Please release a new version like 0.2.6 or 0.2.5.43

### ISSUE THREAD

**Issue by Red54** [DanielAdolfsson/ndppd#90]
0.2.5 is too old and lacks many features.

If you are concerned about stability, you might consider tagging commit eb81b8f as 0.2.5.43 (43 commits after 0.2.5).

This is what SUSE has done for SLE (SUSE Linux Enterprise), and this version has been tested for many years, so stability should not be a problem.

https://github.com/DanielAdolfsson/ndppd/compare/0.2.5...eb81b8f

https://api.opensuse.org/public/source/network/ndppd/ndppd-0.2.5.43.tar.xz

https://packagehub.suse.com/packages/ndppd/

https://build.opensuse.org/package/show/network/ndppd

https://src.opensuse.org/pool/ndppd

**Comment by SpareSimian** [comment]
Some additional work to consider merging here: https://github.com/domosekai/ndppd

**Comment by DanielAdolfsson** [comment]
@Red54 I've tagged that specific commit as 0.2.6.

@SpareSimian I've set up a new branch 0.2.7-devel where I've merged their stuff. This will hopefully be released as 0.2.7- will need to check how stable the changes are.
